# Basic colors
foreground              #dee4e4
background              #0e1415
selection_foreground    #cde7eb
selection_background    #324b4e

# Cursor colors
cursor                  #81d3df
cursor_text_color       #00363c

# URL underline color when hovering with mouse
url_color               #b9c6ea

# Kitty window border colors
active_border_color     #81d3df
inactive_border_color   #3f484a
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #9df0fb
active_tab_background   #004f56
inactive_tab_foreground #bec8ca
inactive_tab_background #1b2122
tab_bar_background      #0e1415

# Colors for marks
mark1_foreground #00363c
mark1_background #81d3df
mark2_foreground #1c3437
mark2_background #b1cbcf
mark3_foreground #23304d
mark3_background #b9c6ea

# The 16 terminal colors
# black
color0 #3f484a
color8 #899294

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #81d3df
color10 #9df0fb

# yellow
color3  #b9c6ea
color11 #d9e2ff

# blue
color4  #b1cbcf
color12 #cde7eb

# magenta
color5  #004f56
color13 #006972

# cyan
color6  #324b4e
color14 #3a4664

# white
color7  #bec8ca
color15 #dee4e4
